* Jeudi 19/05
  - Installation de Débian8 avec Vincent Danjean
  - Mise en place de l'environnement de travail (quelques raccourcis
    qui me sont chers, des marque-pages, un Git:
    https://github.com/FlorianPO/Performance-Regression-Testing)
  - Il faut que je fournisse mon adresse MAC à Christian afin d'avoir
    Internet en filaire (très peu de Wifi dans la salle)
  - Prise en main de Org-mode sous emacs
  
* Lundi 23/05
  - [[https://github.com/FlorianPO/Performance-Regression-Testing/blob/master/Phoronix.org][Overview de Phoronix]] : dépendant du matériel, deux tests n'auront
    du sens que s'ils sont éxecutés sur la /même/ machine.
  - [[https://github.com/FlorianPO/Performance-Regression-Testing/blob/master/CollectiveMind.org][Overview de CollectiveMind]] : plus proche du sujet (axé recherche)
  - [[https://github.com/FlorianPO/Performance-Regression-Testing/blob/master/Jenkins.org][Overview de Jenkins]]

  Ces documents ne sont qu'une ébauche, il conviendra à l'avenir de
  s'intéresser à leur points communs/différences. En première
  approximation, les benchmarks proposés dépendent de la machine qui
  les a générés (à l'exception de CollectiveMind qui semble
  s'intéresser au problème). Néanmoins, ces trois plateformes sont des
  /usines à gaz/, il reste encore énormément à découvrir.

* Mardi 24/05
  - Uniformisation des .org. L'objectif est de comparer les 3
    plateformes sur le benchmarking.
  - Ajout d'un [[https://github.com/FlorianPO/Performance-Regression-Testing/blob/master/State_of_the_art.org][rapport]] /très bref/ sur l'état de l'art. Il convient d'en
    discuter.
  - Réunion avec Arnaud Legrand : creuser les outils pour voir s'ils
    correspondent au besoin (benchmarks propres, possibilité de
    récupérer les données pour une exploitation spécifique, un peu de
    contrôle d'expérience, technologie pérenne). + utiliser Marker
    pour le journal.
  - S'occuper de Pypy, ...
  - Tester Phoronix
  - Installation de Phoronix Test Suite v6.2.1
