#+TAGS: Phoronix(P) Pypy(Y) Jenkins(J) CollectiveMind(C)
#+TAGS: XPFlow(C) Expo(A) Execo(B) 
#+TAGS: Spack(S) Kameleon(K)

* Jeudi 19/05
  - Installation de Débian8 avec Vincent Danjean
  - Mise en place de l'environnement de travail (quelques raccourcis
    qui me sont chers, des marque-pages, un Git:
    https://github.com/FlorianPO/Performance-Regression-Testing)
  - Il faut que je fournisse mon adresse MAC à Christian afin d'avoir
    Internet en filaire (très peu de Wifi dans la salle)
  - Prise en main de Org-mode sous emacs
* Lundi 23/05				    :Phoronix:Jenkins:CollectiveMind:
  - [[https://github.com/FlorianPO/Performance-Regression-Testing/blob/master/Phoronix.org][Overview de Phoronix]] : dépendant du matériel, deux tests n'auront
    du sens que s'ils sont éxecutés sur la /même/ machine.
  - [[https://github.com/FlorianPO/Performance-Regression-Testing/blob/master/CollectiveMind.org][Overview de CollectiveMind]] : plus proche du sujet (axé recherche)
  - [[https://github.com/FlorianPO/Performance-Regression-Testing/blob/master/Jenkins.org][Overview de Jenkins]]

  Ces documents ne sont qu'une ébauche, il conviendra à l'avenir de
  s'intéresser à leur points communs/différences. En première
  approximation, les benchmarks proposés dépendent de la machine qui
  les a générés (à l'exception de CollectiveMind qui semble
  s'intéresser au problème). Néanmoins, ces trois plateformes sont des
  /usines à gaz/, il reste encore énormément à découvrir.
* Mardi 24/05
  - Uniformisation des .org. L'objectif est de comparer les 3
    plateformes sur le benchmarking.
  - Ajout d'un [[https://github.com/FlorianPO/Performance-Regression-Testing/blob/master/State_of_the_art.org][rapport]] /très bref/ sur l'état de l'art. Il convient d'en
    discuter.
  - Réunion avec Arnaud Legrand : creuser les outils pour voir s'ils
    correspondent au besoin (benchmarks propres, possibilité de
    récupérer les données pour une exploitation spécifique, un peu de
    contrôle d'expérience, technologie pérenne). + utiliser Marker
    pour le journal.
  - S'occuper de Pypy, ...
  - Tester Phoronix
  - Installation de Phoronix Test Suite v6.2.1
* Mercredi 25/05						     :ATTACH:
** Phoronix							   :Phoronix:
 :PROPERTIES:
  :Attachments: FirstTest.png SecondTest.png
  :ID:       d5f63874-eef8-49c2-b544-2f7391cd499d
  :END:
   + Premier test avec Phoronix -> rbenchmark -> failed to run properly
   + Deuxième test avec Phoronix -> 7zip compression -> ok
   + Présence de tests multicoeurs
   + L'injection de charges semble possible (see Fulldoc : "stressing
     your system with random workloads") même si ce n'est pas
     l'objectif premier (cf- Vincent)
   + Possibilité d'exporter les données collectées
   + L'interface semble simple à utiliser (même si je n'y suis pas
     arrivé (pour le moment))
   + S'intéresser aux tests eux-même (comment les écrire, etc...)
** Pypy								       :Pypy:
   http://speed.pypy.org/timeline/#/?exe=3,6,1,5&base=2+472&ben=ai&env=1&revs=200&equid=off
   + Fait avec Django (Framework Web python) et Codespeed (Web
     benchmark application) -> à regarder, semble intéressant !
   + Code des benchmarks :
     https://bitbucket.org/pypy/benchmarks/src/846fa56a282b/unladen_swallow/performance/
    
* Jeudi 26/05							       
** Codespeed							       :Pypy:
   https://github.com/tobami/codespeed
   - Problème d'installation (Python invalid syntax (?))
   - La commande magique : =python ./manage.py syncdb --migrate=
   - Serveur lancé : problème d'authentification cependant
   - Il faut créer un super-utilisateur : =python manage.py
     createsuperuser=
   - Lancer le serveur en _sudo_ : =sudo python manage.py runserver 8000=
   - Fournir Codespeed en données : "Codespeed is a web application to
     monitor and analyze the performance of your code" -> seulement de
     la visualisation de données
** Phoronix 							   :Phoronix:
   Résultats des tests dans
   =~/.phoronix-test-suite/test-results/<TEST>/= :
     - =composite.xml= :: : plan d'expérience
     - =system-logs/= :: : 2 tonnes de données collectées
   Méta-données des tests (par défault) dans
   =~/.phoronix-test-suite/test-profiles/pts/<TEST>/=

* Vendredi 27/05
** Phoronix							   :Phoronix:
   - Ecriture d'un bubble sort en python pour tester Phoronix,
     téléchargeable à
     https://github.com/FlorianPO/Performance-Regression-Testing/raw/master/bubble_sort.py.tar.gz
   - Ecriture des méta-données du test (à tester, ne marchera sûrement
     pas du premier coup)
*** Bubble sort TEST
    - placer le test dans :
      =~/.phoronix-test-suite/test-profiles/local/<TEST>/= (celui-ci
      devrait être visible par la commande =phoronix-test-suite
      list-available-tests=
    - il faut générer un checksum MD5 de l'archive à télécharger :
      =md5sum <FILE>= (à placer dans =download.xml=)
    - problème d'éxecutable :
      - le script généré dans install.sh doit avoir le même nom
        =<TEST-NAME>= que le dossier du test =local/<TEST-NAME>=
* Lundi 30/05
** Phoronix							   :Phoronix:
   - Output template : la sortie du programme semble devoir
     correspondre à l'OutputTemplate dans =results-definition.xml=
   - Update : la correspondance doit être exacte (sauf certains cas
     (ex: en C les retours chariot semble ignorés), à étudier...)
   - https://www.phoronix.com/forums/forum/phoronix/phoronix-test-suite/46913-custom-benchmark
*** Multiple results
    - Multiplier les champs =OutputTemplate= dans =results-definition.xml= ne suffit pas...
    - Ce n'est pas possible...
    - Regarder dans le code source -> hardcore
** Autres pistes
   - Execo, XPFlow, Expo
   - Regarder Webinar n°2 + état de l'art de ces outils (voir slide)
     - Regardé jusqu'à 35 min (partie 6)
* Mardi 31/05
** Expo								       :Expo:
*** Intro
    It aims at simplifying the experimental process on such
    distributed platforms. Works with client / server.
    - Liens :
      + http://expo.gforge.inria.fr/
    - Pros :
      + Everything is logged : IO, commands, date, ...
*** Avancement
    - Installation de Ruby
    - Installation de gem2.1
    - Problème de version : Expo et ses dépendances utilisent Ruby
      1.9.3 (current version : Ruby 2.3)
    - Installation de RVM pour installer / switcher Ruby 1.9.3
      + https://rvm.io/rvm/install 
      + http://stackoverflow.com/questions/9919739/how-to-use-the-older-version-of-ruby-1-9-2
      + Pour utiliser la commande =rvm= : =source
        /home/<USER>/.rvm/scripts/rvm= (<USER> : florian)
      + Pour switcher sur Ruby 1.9.3 : =rvm use ruby-1.9.3 --default=
    - Petit tuto Ruby : http://tryruby.org/levels/1/challenges/0
    - Impossible de lancer =./expo= -> problème syntaxe -> passage en
      Ruby 2.3.1
      + IMPOSSIBLE, rien ne marche
      + Expo utilise Ruby 1.8.7 mais Restfully nécessite Ruby >= 1.9.3
** XPFlow							     :XPFlow:
*** Intro
    XPFlow is a new approach to description and execution of
    experiments involving large-scale computer installations. The main
    idea consists in describing the experiment as workflow and using
    achievements of Business Workflow Management to reliably and
    efficiently execute it. Moreover, to facilitate the design
    process, the framework provides abstractions that hide unnecessary
    complexity from the user.
    - Liens:
      + http://xpflow.gforge.inria.fr/
      + http://xpflow.gforge.inria.fr/img/slides/slides.pdf
	* http://xpflow.gforge.inria.fr/img/slides/slides.pdf
*** Avancement
    - Installation de XPFlow
    - Lecture des slides : pas dégueux du tout
    - Permet de lancer des commandes systèmes, etc...
    - Installation de =cairo= : =gem install cairo= (pour exporter en pdf)
      + permet de visualiser le workflow
    - A tester avec Grid5000 -> demande de compte faite.
** Execo							      :Execo:
*** Intro
    Execo is a Python library that allows you to finely manage unix
    processes on thousands of remote hosts. It is well designed for :
    - prototyping experiments on distributed systems (Grid5000
      support)
    - automatize admin tasks
    - create reproducible experiments
    - Liens :
      + http://execo.gforge.inria.fr/doc/latest-stable/
      + http://execo.gforge.inria.fr/doc/latest-stable/userguide.html
*** Avancement
    - Installation de Execo et de tous ses packages optionnels.
* Mercredi 01/06
** Execo							      :Execo:
  - Obtention d'un compte Grid5000
  - Lecture de la doc d'Execo
  - A faire : comparer Execo et XPFlow
** XPFlow							     :XPFlow:
   - Liste des patterns : http://xpflow.gforge.inria.fr/docs/patterns/ :
     super cool !
   - =git clone= du projet
   - Installation de LaTeX-mk pour générer la doc
   - Recherche de la structure du pattern =info= : classe InfoRun dans
     runs.rb (peu de choses...)
* Mardi 07/06
  - Visionnage des webinars 2 et 3
  - Contacter Olivier Richard et Michael Mercier au sujet de
    l'installation d'environnement. XPFlow mélange celui-ci et le
    contrôle de l'expérience : pas une bonne idée.
* Mercredi 08/06
  - Installation de =emacs= sur Windows (=C-H v user-init-file RET= dans
    emacs pour trouver l'emplacement du fichier =.emacs=)  
  - Visionnage du webinar 1 + [[https://github.com/FlorianPO/Performance-Regression-Testing/blob/master/Webinar_1.org][prise de note]]
* Jeudi 09/06
  - Visionnage du webinar 2 + [[https://github.com/FlorianPO/Performance-Regression-Testing/blob/master/Webinar_2.org][prise de note]]
  - Docker for reproducible research :
    http://www.carlboettiger.info/assets/files/pubs/10.1145/2723872.2723882.pdf
  - SPACK + KAMELEON -> téléchargement (+ installation)
    - SPACK : Lucas 
    - Dépendances : Venìcius
    - KAMELEON : Michael
  - (XPFlow) -> Contrôle de l'expérience
* Vendredi 10/06
** Spack							      :Spack:
   Petits tutos sur le PATH pour se mettre à niveau :
   - https://wiki.debian.org/EnvironmentVariables
   - http://www.generation-linux.fr/index.php?post/2008/10/15/Changer-les-dossiers-par-defaut-dans-le-PATH
   Installation de Spack
*** Liens :
    - Features :: http://software.llnl.gov/spack/features.html
    - Doc :: http://software.llnl.gov/spack/
    - Package installable ::
         http://software.llnl.gov/spack/basic_usage.html
** Kameleon							   :Kameleon:
   Installation de Kameleon
*** Liens :
    - Doc :: http://kameleon.imag.fr/index.html
* Lundi 13/06
** Kameleon							   :Kameleon:
   - Le tutoriel qui va bien :
     http://kameleon.imag.fr/grid5000_tutorial.html
   - Kameleon + Puppet :
     https://www.grid5000.fr/mediawiki/index.php/Environments_creation_using_Kameleon_and_Puppet
** Spack							      :Spack:
   - http://software.llnl.gov/spack/basic_usage.html
* Mardi 14/06
  - Lecture complète de la doc de Kameleon : fait.
  - Réunion avec Michael et Arnaud :
    + Préliminaires :      
      * Lire le /Getting started/ de G5k
        https://www.grid5000.fr/mediawiki/index.php/Getting_Started
      * Déployer une image, jouer avec les commandes, ...
      * Objectif : lancer au moins un benchmark StarPU Morse
        http://starpu.gforge.inria.fr/testing/morse/trunk/morse.html
    + Automatiser : 
      * Kameleon + Spack (pour les BLAS)
      * récupérer sur Git StarPU / Morse
      * benchmark sur les versions (en mode réel ou simulé)
	- mode simulé : éxecution des versions parallèles (Execo
          peut-il faire ceci ? Voir avec Michael)
      * logger
** Grid5000 getting started
*** Réservation
    - Dabord, la frontale :
      #+begin_src sh :session foo :results output :exports both 
      ssh fpopek@access.grid5000.fr
      #+end_src

      #+RESULTS:
      #+begin_example

      Linux access-south.grid5000.fr 3.2.0-4-amd64 #1 SMP Debian 3.2.73-2+deb7u3 x86_64
      ----- Grid'5000 - access-south.grid5000.fr -----

      Welcome to Grid'5000

      ** Connect to a site:
      ssh {grenoble,lille,luxembourg,lyon,nancy,nantes,reims,rennes}

      ** Useful links:
       - account management (password change): https://api.grid5000.fr/ui/account
       - homepage: https://www.grid5000.fr/mediawiki/index.php/Category:Portal:User
       - charter : https://www.grid5000.fr/mediawiki/index.php/Grid5000:UserCharter
       - support : https://www.grid5000.fr/mediawiki/index.php/Support

      ** Data on access.grid5000.fr :
       - your home directory on access machines (access-north and access-south)
	 is not synchronized and should not be use to store data.
       - please use ssh forwarding to send data directly to sites or
      scp files login@access.grid5000.fr:reims/ using the nfs mount point in your home

      [31m[5m
      ** Warning: 1 event in progress
      #Incident in #Sophia : hard drive failures on srv.sophia.grid5000.fr, site unavailable
      [0m[31m    https://intranet.grid5000.fr/bugzilla/show_bug.cgi?id=6967
      [0m
      Last login: Tue Jun 14 14:39:37 2016 from 129.88.54.126
#+end_example

    - Puis grenoble :
      #+begin_src sh :session foo :results output :exports both 
      ssh grenoble
      #+end_src

      #+RESULTS:
      #+begin_example
      ----- Grid'5000 - Grenoble - fgrenoble.grenoble.grid5000.fr -----

      This site has 3 clusters (see: https://api.grid5000.fr/stable/ui/visualizations/nodes.html)

      Available in queue default:
       - genepi (2008): 34 nodes (2 CPUs Intel Xeon E5420, 4 cores/CPU, 8GB RAM, 153GB HDD)
       - edel   (2008): 72 nodes (2 CPUs Intel Xeon E5520, 4 cores/CPU, 24GB RAM, 119GB SSD)
       - adonis (2010): 10 nodes (2 CPUs Intel Xeon E5520, 4 cores/CPU, 24GB RAM, 233GB HDD)

      ** Useful links:
       - account management (password change): https://api.grid5000.fr/ui/account
       - homepage: https://www.grid5000.fr/mediawiki/index.php/Category:Portal:User
       - charter : https://www.grid5000.fr/mediawiki/index.php/Grid5000:UserCharter
       - support : https://www.grid5000.fr/mediawiki/index.php/Support

      ** Others sites:
      ssh {lille,luxembourg,lyon,nancy,nantes,reims,rennes,sophia}

      Last login: Tue Jun 14 14:40:46 2016 from access-south.grid5000.fr
#+end_example

    - =oarsub -I= pour réserver une machine en mode interactif
    - Pour réserver 2 noeuds pendant 30 min :
      #+begin_src sh :session foo :results output :exports both 
      oarsub -I -l nodes=2,walltime=0:30 
      #+end_src

    - Pour réserver dans le futur
      #+begin_src sh :session foo :results output :exports both 
      oarsub -I -r '2012-12-23 16:30:00'
      #+end_src

      + =oarstat= pour voir l'historique des réservations
      + =oarstat -u= pour voir ses réservations
      + =oarstat -r <JOB_ID>= pour supprimer une réservation
    - Propriétés OAR
      #+begin_src sh :session foo :results output :exports both 
      oarsub -p "gpu='YES'"
      #+end_src

    - =oarsub -t deploy= pour déployer avec Kadeploy (/The root password
      for all Grid'5000-provided images is grid5000/)
*** Gestion des noeuds
    - =uniq $OAR_NODEFILE= liste des noeuds réservés
    - =oarsh <NODE>= utiliser un noeud réservé
    - =ssh root@<NODE>= se connecter en root sur un noeud
** Spack
   Installation :
   - =git clone https://github.com/llnl/spack.git=
   - =export PATH=$SPACK_ROOT/bin:$PATH=
   - =spack install libelf=
** StarPU
*** Installation avec Spack
    http://morse.gforge.inria.fr/chameleon/tuto_chameleon/chameleon-tutorial-2015-12-16-inria.html#sec-6-2
*** En pratique (buggué)
    Déploiement

    #+begin_src sh :session foo :results output :exports both 
    ssh grenoble.g5k (ou ssh fpopek@access.grid5000.fr puis ssh grenoble)
    ssh digitalis
    oarsub -I -t deploy
    kadeploy3 -f $OAR_NODE_FILE -e jessie-x64-big -k (problème avec Digitalis)
    ssh root@machine
    #+end_src
    
    Installation de Spack
    
    #+begin_src sh :session foo :results output :exports both 
    git clone https://github.com/fpruvost/spack
    export SPACK_ROOT=~/spack/
    export PATH=$SPACK_ROOT/bin:$PATH
    #+end_src
      
    Morse package
    
    #+begin_src sh :session foo :results output :exports both 
    cd spack
    git checkout morse
    #+end_src
    
    Installation de Chameleon

    #+begin_src sh :session foo :results output :exports both 
    spack install chameleon+examples
    #+end_src

    Installation de StarPU

    #+begin_src sh :session foo :results output :exports both 
    spack install -v chameleon@trunk~quark+examples+fxt ^starpu@svn-trunk+fxt
    spack install -v chameleon@trunk~quark+simu+examples+fxt ^starpu@svn-trunk+simgrid+fxt ^simgrid@starpumpi (pour la simulation)

    ( spack install -v chameleon@trunk~quark+examples+fxt )
    #+end_src
* Mercredi 15/06
  - Ma version de Spack ne permet pas d'installer StarPu (0.9.1) celle
  de Vinìcius (0.8.15) marche
  - Problème d'import Python -> récupération de l'image de Vinìcius
  - Problème de Spack -> envoie d'un mail à Lucas
** Environnement de Vinìcius
   #+begin_src sh :session foo :results output :exports both 
   ssh grenoble.g5k
   ssh digitalis
   oarsub -I -t deploy
   kadeploy3 -f $OAR_NODE_FILE -a imageIDCin.env -k
   #+end_src
  
   Image copiée depuis =/home/vgarciapinto/= (avec modification de
   imageIDCin.env avec mon login)

   #+begin_src sh :session foo :results output :exports both 
   ssh root@machine
   sudo apt-get update
   sudo apt-get install -y python2.7-dev
   sudo apt-get install -y vim emacs
   sudo apt-get install -y curl patch
   sudo apt-get install -y git subversion mercurial
   sudo apt-get install -y build-essential gfortran
   sudo apt-get install -y autoconf automake cmake cmake-data doxygen texinfo
   sudo apt-get install -y libtool libtool-bin
   sudo apt-get install -y libboost-dev
   sudo apt-get install -y gawk
   sudo apt-get install -y bison flex
   sudo apt-get install -y binutils-dev libelf-dev libiberty-dev
   sudo apt-get install -y libz-dev
   sudo apt-get install -y libqt4-dev freeglut3-dev
   sudo apt-get install -y environment-modules
   #+end_src

   #+begin_src sh :session foo :results output :exports both 
   git clone https://github.com/fpruvost/spack
   export SPACK_ROOT=~/spack/
   export PATH=$SPACK_ROOT/bin:$PATH
   #+end_src

   #+begin_src sh :session foo :results output :exports both 
   cd spack/
   git checkout morse
   #+end_src

   La branche morse peut (sous quelles conditions ?) ne pas marcher :

    #+RESULTS:
    #+begin_example
   Traceback (most recent call last):
     File "/root/spack//bin/spack", line 50, in <module>
       import nose
     File "/root/spack/lib/spack/external/nose/__init__.py", line 1, in <module>
       from nose.core import collector, main, run, run_exit, runmodule
     File "/root/spack/lib/spack/external/nose/core.py", line 9, in <module>
      import unittest
     File "/usr/lib/python2.7/unittest/__init__.py", line 58, in <module>
      from .result import TestResult
     File "/usr/lib/python2.7/unittest/result.py", line 10, in <module>
      from functools import wraps
   ImportError: cannot import name wraps
   #+endexample

   #+begin_src sh :session foo :results output :exports both 
   spack install chameleon
   #+end_src

   #+begin_src sh :session foo :results output :exports both 
   spack install -v chameleon@trunk~quark+examples+fxt ^starpu@svn-trunk+fxt
   #+end_src

   ==> Error: chameleon does not depend on starpu
