* Jenkins
** Overview
*** Intro
    The leading open source automation server, Jenkins (Hudson
    successor) provides hundreds of plugins to support building,
    deploying and automating any project. Jenkins is an automation
    engine with an unparalleled plugin ecosystem to support all of
    your favorite tools in your delivery pipelines, whether your goal
    is continuous integration, automated testing, or continuous
    delivery. With the introduction of the Pipeline plugin, users now
    can implement a project's entire build/test/deploy pipeline in a
    Jenkinsfile and store that alongside their code, treating their
    pipeline as another piece of code checked into source control.
*** License
    MIT license
*** Last version
    Jenkins 2.6
*** Operating systems
    Jenkins can be installed on Windows, Ubuntu/Debian, Red
    Hat/Fedora/CentOS, Mac OS X, openSUSE, FReeBSD, OpenBSD, Gentoo.
*** Written in
    Java
*** Links
**** Jenkins
     - Quick guide : http://www.tutorialspoint.com/jenkins/jenkins_quick_guide.htm
     - Overview (slide) : http://fr.slideshare.net/AhmedMGomaa/jenkins-overview Wiki :
     - Wiki : https://en.wikipedia.org/wiki/Jenkins_%28software%291

** Features
   - Easy installation / configuration
   - Rich plugin ecosystem
   - Extensibility : Most parts of Jenkins can be extended and
     modified, and it's easy to create new Jenkins plugins. This
     allows you to customize Jenkins to your needs.
   - Distributed builds : Jenkins can distribute build/test loads to
     multiple computers with different operating systems. Building
     software for OS X, Linux, and Windows ? No problem.
   - Based on -lots of- different tools : Maven, Git, Tomcat, ...
   
** Benchmarking
   Benchmarking and data visualization with plugins
   (https://wiki.jenkins-ci.org/display/JENKINS/Performance+Plugin)

** Résumé
   Outil d'intégration continue, très modulable. Permet de faire
   coexister de nombreux outils. Moins orienté benchmark que Phoronix
   ou CollectiveMind.
